backend:
  name: git-gateway
  branch: main
media_folder: "images"
publics_folder: "/images"
collections:
  - name: "students"
    label: "Students"
    folder: "students"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Student name", name: "name", widget: "string" }
      - {
          label: "Context",
          name: "context",
          widget: "select",
          options:
            [
              "Digital Context",
              "Autonomous Context",
              "Applied Context",
              "Socio-Political Context",
            ],
        }
      - { label: "Thumbnail Image", name: "thumb_image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
